# Generated by Django 4.2.7 on 2025-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_hash'], name='files_filem_file_ha_4cd3ea_idx'), models.Index(fields=['name'], name='files_filem_name_776afd_idx'), models.Index(fields=['uploaded_at'], name='files_filem_uploade_bbe264_idx')],
            },
        ),
    ]
